chegadas:
  - fila_entrada: Fila1
    min_chegada: 2.0
    max_chegada: 4.0

filas:
  - nome: Fila1
    servidores: 1
    capacidade: 5
    min_servico: 1.0
    max_servico: 2.0
  
  - nome: Fila2
    servidores: 2
    capacidade: 5
    min_servico: 4.0
    max_servico: 6.0
  
  - nome: Fila3
    servidores: 2
    capacidade: 10
    min_servico: 5.0
    max_servico: 15.0

rede:
  - origem: Fila1
    destino: Fila2
    probabilidade: 0.8
  
  - origem: Fila1
    destino: Fila3
    probabilidade: 0.2
  
  - origem: Fila2
    destino: Fila1
    probabilidade: 0.3
  
  - origem: Fila2
    destino: Fila3
    probabilidade: 0.5
  
  - origem: Fila2
    destino: SAIDA
    probabilidade: 0.2
  
  - origem: Fila3
    destino: Fila2
    probabilidade: 0.7
  
  - origem: Fila3
    destino: SAIDA
    probabilidade: 0.3

config:
  warmup: 1000.0
  observacao: 10000.0
  replicacoes: 5
